### ISSUE TITLE
No longer working for the current version of IAVH

### ISSUE THREAD

**Issue by captain-soban** [SteffenL/Van-Helsing-game-research#1]
Looks like the storage file has been reworked by Neocore. The application can no longer read the storage file. Would really like to see this updated. Your app looked really awesome when it worked. I hope you have the time to update this.

**Comment by SteffenL** [comment]
Hello! Thank you for the feedback and for reporting this. Unfortunately, I can't say exactly when I'll be able to make time for checking out what changed since I have a project going on at the moment, but I'll leave the issue open for now.

**Comment by SteffenL** [comment]
I've had a look at the new file format. I don't yet know what the new stuff is used for, but in the function `StorageGameSaveReader::readItem()`, adding this at the end makes it possible to load the file `storage.sav` again:

```
// Experiment for v1.4.0c of the game
{
    stream.Read<int>();
    auto v1 = stream.Read<int>();
    if (v1 > 0) {
        stream.Read<int>();
        stream.Read<int>();
    }

    stream.Read<char>();
    stream.Read<int>();
    stream.Read<short>();
    stream.Read<int>();
    stream.Read<short>();
    stream.Read<int>();
    stream.Read<int>();
    stream.Read<int>();
    stream.Read<int>();
    stream.Read<short>();
    stream.Read<int>();
    stream.Read<int>();
    stream.Read<short>();
    stream.Read<int>();
    stream.Read<int>();
    stream.Read<float>();
    stream.Read<float>();
}
```

At least this was the "pattern" I saw with my `storage.sav` file, but it would be good to test with more files. Do you perhaps have a `storage.sav` you're willing to share with me?

**Comment by SteffenL** [comment]
I've noticed something. I quite clearly recall from the last time I played the game (version 1.0.5 maybe) that my modded gear was very overpowered. Now, in version 1.4.0c of the game, the same gear has really poor stats in comparison. Unless I recall incorrectly, it seems like the game may have more checks in place to kill overpowered gear.

**Comment by SteffenL** [comment]
I've improved the artifact enchantment editor a bit, and you can now have more control over the intensity of their effects. The latest code in the development branch should be stable enough to test. Very old versions of the game are currently not supported. Just let me know if you want to give it a try unless you wish to compile it on your own.

**Comment by captain-soban** [comment]
Thank you for updating! I'd love to give it a try. Could you compile it for me or leave instructions how to? I have limited programming knowledge.

**Comment by SteffenL** [comment]
You may try the [new version](/SteffenL/Van-Helsing-game-research/releases/latest).

I might as well let you know that it started becoming an annoyance to work with WTL, so I've started rewriting the GUI code with wxWidgets instead, and that means that the quality of the UI will improve quite a bit. Just thought it would be worth mentioning that since the current public release doesn't have all the features a proper editor should have.

**Comment by SteffenL** [comment]
Would be nice for me to know whether it worked as expected or not; otherwise, I'll just assume that it did.

**Comment by SteffenL** [comment]
I've released a [new version](/SteffenL/Van-Helsing-game-research/releases/tag/release%2Fv0.3) with many fixes and improvements. Please create a new issue if you still have issues.

**Comment by captain-soban** [comment]
Thanks for the updates! I actually stopped playing this game but having your program makes me play it again. Something notes though if you're still interested.
1. Some of the enhancements aren't  showing up.
2. The value index and scale don't seem to match the description (I might have misunderstood this)
![enhancements not displayed](https://cloud.githubusercontent.com/assets/3745362/8651779/9b524910-29ad-11e5-954c-ad6625618b6a.jpg)

**Comment by SteffenL** [comment]
Thank you for letting me know!

The value index usually goes up to 15, and anything beyond is undefined behavior (but can give some fun values). Each enchantment has an array of minimum values, and usually an array of maximum values. The "value index" is an index in these arrays. For example, an array may be specified as "1,2,4,6,8", where 0 is the index of value 1, 1 is the index of value 2, 2 is the index of value 4, etc.

The "value scale" scales the value between the minimum and maximum value specified in the mentioned arrays. For example, a minimum value may be 10 and the maximum 15. A scale of 0 means 0% = 10; a scale of 1 means 100% = 15.

I've specified the formula here: [Game formulas](/SteffenL/Van-Helsing-game-research/wiki/Game-formulas)

Regarding the missing text: That should probably not happen. Would you mind sharing your `storage.sav` file with me so that I can check it out?

Please feel free to e-mail me in private: steffenl.sw at gmail dot com

Thank you!
